apiVersion: apps/v1
kind: Deployment
metadata:
  name: voyage-api
  labels:
    app: voyage-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: voyage-api
  template:
    metadata:
      labels:
        app: voyage-api
    spec:
      containers:
      - name: api
        image: ghcr.io/alvira-parveen/voyage-analytics-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: API_KEY
          value: "voyage-dev-key-2024"
        - name: MODELS_PATH
          value: "models"
        - name: LOG_LEVEL
          value: "INFO"
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: voyage-api-service
spec:
  selector:
    app: voyage-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
